# This tool allows the user to improve their French writing ability by repeatedly responding to questions randomly generated
# Created by: Daniel Berrones [email: Daniel.A.Berrones@gmail.com]


from random import choice


class FrenchQuestions:
    def __init__(self):
        self.questions = [
            "Que manges-tu? ",
            "Qui frappe à la porte maintenant? ",
            "À qui penses-tu? ",
            "Chez qui vas tu? Et avec qui? ",
            "Sur qui peux-tu compter? ",
            "Quand iras-tu te doucher? ",
            "Depuis quand est-ce que vous ne l'avez pas vu? ",
            "De quoi as-tu besoin? ",
            "Maintenant, je fais quoi? ",
            "Où vas-tu dormir ce soir ?",
            "Pourquoi as-tu peur? ",
            "Comment? Je ne vous comprends pas? ",
            "Que fais-tu demain? ",
            "Est-ce que tu peux dîner avec nous plus tard? ",
            "Voulez-vous que je vous prête ce livre? ",
            "Avez-vous lu ce livre? ",
            "Qui te parle? ",
            "Pourquoi elle pleure? ",
            "Est-ce que tu m'entends?",
            "Sur qui pouvons-nous compter? ",
            "Vous venez d'où? ",
            "Quand viendras-tu ?",
            "Quel jour sommes-nous? ",
            "Qu'est-ce que ça veut dire? ",
            "Pourquoi tu as dit cela? ",
            "Est-ce que tu m'aimes? ",
            "Pourquoi il a beaucoup pleuré ce soir? ",
            "Est-ce que tu comprends le français? ",
            "Est-ce que tu aimes le chocolat? ",
            "Est-ce que tu vas souvent à la plage? ",
            "Qui est là? ",
            "Que faut-il faire? ",
            "Pourquoi es-tu en colère? ",
            "Comment est ton chien avec les gens? ",
            "Combien ça coûte? ",
            "Quel est ton pays préféré? ",
            "Qui êtes-vous? ",
            "Que voulez-vous faire? ",
            "Pourquoi fait-il cela? ",
            "Où es-tu? ",
            "Où partez-vous en vacances cette année?",
            "Quelle heure est-il s'il te plaît? ",
            "Comment s'appelle ton petit chat? ",
            "Quel âge as-tu? ",
            "Qui a cassé mon portable? ",
            "Où est passé mon frère, tu ne l'as pas vu? ",
            "Où vas-tu aller? ",
            "Quelle est la capitale de la France? ",
            "Où habites-tu? ",
            "Comment t'appelles-tu? ",
            "Que faites-vous ici? ",
            "Quel est ton vrai nom? ",
            "Quels films aimeriez-vous voir? ",
            "Qu'est-ce qui se passe? ",
            "Pouvez-vous me donner un morceau de pain, s'il vous plaît?",
            "Peux-tu me conduire à Paris ce soir?",
            "Est-ce que vous auriez une chambre de libre pour la nuit?",
            "Qu'est-ce que Laurent a donné à Marie?",
            "Où est le livre que tu m'as donné?",
            "Depuis quand les enfants jouent-ils dans le jardin?",
            "Avec qui est-ce que je pars en vacances?",
            "Quel musique aimes-tu écouter?",
            "Tu es libre?",
            "Quel temps fait-il?",
            "Quel âge a ton père?",
            "Que fait-tu pour demain?",
            "Que faisons-nous maintenant?",
            "Quel est le métier de ton père?",
            "Qui est-ce qui part?",
            "Partez-vous?",
            "Comment va-t-elle aujourd'hui?",
            "Suis-je en retard pour mon rendez-vous?",
            "Comment vas-tu à Rome?",
            "Comment va ton frère?",
            "Comment va ta mère?",
            "As-tu envie d'aller te promener?",
            "Ai-je envie de parler avec ma mère?",
            "Ont-ils vraiment besoin de manger autant? ",
            "Pourquoi ne veux-tu pas m'aider?",
            "Que ferons-nous aujourd'hui?",
            "Quand veux-tu venir?",
            "Est-ce que tu peux me dire pourqoui?",
            "Tu pars quand?",
            "Quand est-ce que tu m'écouteras?",
            "Quand est-ce que tu vas te taire?",
            "Comment vas-tu depuis tout ce temps?",
            "Où es-tu sur la photo, je ne te vois pas?",
            "Que fais-tu ce matin?",
            "Qui veut m'aider?",
            "Qui veut me parler?",
            "Qui aura besoin de faire ça?",
            "Quoi? Je ne t'entends pas!",
            "Qui a pris le téléphone?",
            "Qui a appelé ce matin?",
            "Que se passe-t-il?",
            "Qui a frappé à ta porte?",
            "Quand est-ce que le gâteau sera cuit?",
            "Qu'est-ce qui m'arrive ce soir?",
            "Qui a allumé la radio?",
            "Qui veut dîner ce soir avec nous?",
            "Qui a perdu son chat?",
            "Qui aime nager?",
            "Que veut-elle faire plus tard comme métier?",
            "Quelles langues parlez-vous?",
            "Quelle heure prend-elle le train?",
            "Quelle heure peut-on l'appeler?",
            "Quel est le nom de ta copine?",
            "Qui a mangé le dernier morceau de gâteau?",
            "Quoi de neuf depuis une semaine?",
            "Est-ce que'elles ont des frères?",
            "Que film est-ce que tu préféres?",
            "Est-ce que vous buvez souvent du café?",
            "Pourquoi est-ce qu'elle apprend le français?",
            "Où vont-ils si tôt?",
            "Quand est-ce que tes amis arriveront?",
            "Qui est-ce qui vient se promener avec moi?",
            "A quel moment prenez-vous votre déjeuner?",
            "Que cherches-tu?",
            "Pourquoi as-tu voulu faire cela?",
            "Veux-tu que je m'en aille?",
            "Veux-tu que je te le dise?"]

    def prompt(self):
        for x in self.questions:
                print(choice(self.questions))
                input()


def main():
    writing = FrenchQuestions()
    writing.prompt()


if __name__ == '__main__':
    main()